/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          50: '#f0f9ff',
          100: '#e0f2fe',
          200: '#bae6fd',
          300: '#7dd3fc',
          400: '#38bdf8',
          500: '#0ea5e9',
          600: '#0284c7',
          700: '#0369a1',
          800: '#075985',
          900: '#0c4a6e',
        },
        secondary: {
          50: '#fdf4ff',
          100: '#fae8ff',
          200: '#f5d0fe',
          300: '#f0abfc',
          400: '#e879f9',
          500: '#d946ef',
          600: '#c026d3',
          700: '#a21caf',
          800: '#86198f',
          900: '#701a75',
        },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'Fira Code', 'monospace'],
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-in-out',
        'slide-up': 'slideUp 0.3s ease-out',
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
      },
    },
  },
  plugins: [require("daisyui")],
  daisyui: {
    themes: [
      {
        light: {
          "primary": "#0ea5e9",
          "secondary": "#d946ef",
          "accent": "#37cdbe",
          "neutral": "#3d4451",
          "base-100": "#ffffff",
          "info": "#3abff8",
          "success": "#36d399",
          "warning": "#fbbd23",
          "error": "#f87272",
        },
        dark: {
          "primary": "#0ea5e9",
          "secondary": "#d946ef",
          "accent": "#37cdbe",
          "neutral": "#3d4451",
          "base-100": "#1f2937",
          "info": "#3abff8",
          "success": "#36d399",
          "warning": "#fbbd23",
          "error": "#f87272",
        },
        retro: {
          "primary": "#ff6b6b",
          "secondary": "#4ecdc4",
          "accent": "#45b7d1",
          "neutral": "#2c3e50",
          "base-100": "#f8f9fa",
          "info": "#3498db",
          "success": "#2ecc71",
          "warning": "#f1c40f",
          "error": "#e74c3c",
        },
        terminal: {
          "primary": "#00ff00",
          "secondary": "#ff00ff",
          "accent": "#ffff00",
          "neutral": "#1a1a1a",
          "base-100": "#000000",
          "info": "#00ffff",
          "success": "#00ff00",
          "warning": "#ffff00",
          "error": "#ff0000",
        },
        matrix: {
          "primary": "#00ff41",
          "secondary": "#008f11",
          "accent": "#003b00",
          "neutral": "#1a1a1a",
          "base-100": "#000000",
          "info": "#00ff41",
          "success": "#00ff41",
          "warning": "#ffff00",
          "error": "#ff0000",
        },
      },
    ],
    darkTheme: "dark",
    base: true,
    styled: true,
    utils: true,
    prefix: "",
    logs: true,
    themeRoot: ":root",
  },
} 